[options]
packages =
    google
    google.genai
    google.genai.types
    google.genai.tests
    google.genai.tests.afc
    google.genai.tests.batches
    google.genai.tests.caches
    google.genai.tests.chats
    google.genai.tests.client
    google.genai.tests.common
    google.genai.tests.errors
    google.genai.tests.files
    google.genai.tests.live
    google.genai.tests.local_tokenizer
    google.genai.tests.mcp
    google.genai.tests.models
    google.genai.tests.operations
    google.genai.tests.public_samples
    google.genai.tests.shared
    google.genai.tests.shared.batches
    google.genai.tests.shared.caches
    google.genai.tests.shared.chats
    google.genai.tests.shared.files
    google.genai.tests.shared.models
    google.genai.tests.shared.tunings
    google.genai.tests.tokens
    google.genai.tests.transformers
    google.genai.tests.tunings
    google.genai.tests.types
include_package_data = True
